name: Release App
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release

      - name: Publish image ST
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.ST_DOCKER_USER }}
          password: ${{ secrets.ST_DOCKER_PASSWORD }}
          path: .
          registry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
          repository: exchange/position-manager
          tags: latest
          add_git_labels: true
          build_args: app_version=exchange.position-manager:latest,app_compilation_date=${{ steps.current-time.outputs.formattedTime }}