name: Release App
on:
  push:
    tags: "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release

      - name: Publish image ST
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: ./publish-api
          registry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
          repository: myjettools/position-manager
          tag_with_ref: true
          build_args: app_version=position-manager:${{ steps.extract_branch.outputs.tags }},app_compilation_date=${{ steps.current-time.outputs.formattedTime }}


